### PR TITLE
game over scene in intro_maze with new game and restart buttons

### PR DESCRIPTION
**Pull request by nhford**
Canvas-GameOver gameobject appears once collides with mummy
Offers new game (loads intro_outdoor) and quit (which quits both in editor and on build)

TODO:
loads start scene instead of intro_outdoor?
freeze game once collision -> but i imagine that has to do with death animations etc.

### CODE REVIEW

**Comment by aarav-nair** [comment]
The placeholders X do not change
image

**Comment by nhford** [comment]
that should be fixed now Aarav.

**Review by mnhegde — COMMENTED** [review]
If we hit play again should total duration reset? When I play again it seems like the timer isn't reset to 0 so it keeps increasing although not sure if that's intended

**Comment by mnhegde** [comment]
Too many merge conflicts, small-fixes branch now has end game screen

**Pull request closed without merging**
