### PR TITLE
Main and Pause Menus

### PR DESCRIPTION
**Pull request by aarav-nair**

### CODE REVIEW

**Review by VinT04 — CHANGES_REQUESTED** [review]
Don't delete anything deemed unnecessary for the time being, we might particles for later sections in the game since we're rebasing branch on top

**Review by mnhegde — DISMISSED** [review]
I think we should gitignore the json files, it gives more opportunities for package conflicts. pretty sure solution file keeps track of dependencies so just having that should be enough?

**Comment by aarav-nair** [comment]
> Don't delete anything deemed unnecessary for the time being, we might particles for later sections in the game since we're rebasing branch on top

What did I delete?

**Comment by aarav-nair** [comment]
> I think we should gitignore the json files, it gives more opportunities for package conflicts. pretty sure solution file keeps track of dependencies so just having that should be enough?

I don't think I can gitignore files that I have already changes, but I can delete them from this branch if you would like

**Review by VinT04 — DISMISSED** [review]

**Review by mnhegde — APPROVED** [review]
LGTM

**Review by VinT04 — APPROVED** [review]
LGTM

**Pull request merged**
